### ISSUE TITLE
MinHook 

### ISSUE THREAD

**Issue by bassnbru** [Pocakking/BigBaseV2#1]
MinHook\MinHook.lib cannot be inputted. Fix?

**Comment by DanielMaywood** [comment]
you gotta get it yourself

@Pocakking doesn't know how to do dependencies in git projects apparently

**Comment by bassnbru** [comment]
Pocakking you also forgot StackWalker.lib, but the problem with this one is I cant this online. Poca plz just update the source with linked files included. Or links work.

**Comment by DanielMaywood** [comment]
Go find the project and compile it yourself my dood.

I'm assuming it's this project: https://github.com/JochenKalmbach/StackWalker
