### ISSUE TITLE
Can't build - 36 errors

### ISSUE THREAD

**Issue by Eddcapone** [Pocakking/BigBaseV2#18]
I tried to build the project, but I get alot of errors. Is this project dead?

![image](https://user-images.githubusercontent.com/16349349/121560496-ddd95b00-ca17-11eb-84e2-7c50542f6b89.png)

**Comment by PatchByte** [comment]
if you can't read the readme it's your fault

**Comment by HasseM** [comment]
Use GIT to also get the needed submodules!

git clone https://github.com/Pocakking/BigBaseV2.git --recurse-submodules

**Comment by Baugle** [comment]
use git
