### ISSUE TITLE
Crashes on injection

### ISSUE THREAD

**Issue by Vistril** [Pocakking/BigBaseV2#20]
Yeah-- I get this thing is ancient by now. I tried updating the natives to latest.. still nothing.

I'm a bit new to this sorta stuff, I'll admit.
Builds in VS just fine.
I injected using Stand Menu's injector, and BasicInjector. 
Seems Stand Menu's injector gets BigBase to run, meaning it can open it's CMD window, but the game crashes.
BasicInjector errors out and nothing happens.

Built on VS2019, Windows 11 22000.258.

Has anyone gotten BigBase properly working on GTA 1.57?

**Comment by xSolar123** [comment]
inside of main.cpp, under dllmain, you will see this 

```
-   if (*g_pointers->m_game_state != eGameState::Playing)
-                 {
-                     LOG_INFO("Waiting for the game to load.");
-                     do
-                     {
-                         std::this_thread::sleep_for(100ms);
-                     } while (*g_pointers->m_game_state != eGameState::Playing);
- 
-                     LOG_INFO("The game has loaded.");
-                 }
-                 else
-                 {
-                     LOG_INFO("The game is already loaded.");
-                 }
```

delete this and try to inject again, see if this fixes your issue.

**Comment by Vistril** [comment]
Will try this when I get the chance. Keep ya posted.

**Comment by Vistril** [comment]
Fixed it. Thank you for the fix, xSolar!
