### ISSUE TITLE
Cannot use __try in functions that require object unwinding

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [Pocakking/BigBaseV2#7]
I get this error when I build the source: Cannot use __try in functions that require object unwinding

**Comment by Sainan** [comment]
![image](https://user-images.githubusercontent.com/63328889/81564294-d02a4f80-9397-11ea-80c6-3684c3f410ce.png)

**Comment by ghost** [comment]
Or you just turn it from Debug to Releases!
https://i.imgur.com/sKnpsS1.png
