### ISSUE TITLE
Hey i am new with this base!

### ISSUE THREAD

**Issue by ghost** [Pocakking/BigBaseV2#8]
Hello my name is Hendrik,
currently i am using the nano base 👎 and i dont like the base you know!
I have some questions.

# Question 1
How do i use scriptGlobal i tried it but i failed so i want to ask.
In the Nano base you use globalHandle like this:
```c++
globalHandle(~~~~~).At(~~~).As<~~~>() = ~~~;
```
I already looked at it in bigbase v2.
But i still get some errors.
How do i use it in BigBase v2?

# Question 2
How do i create hooks i already tried but i failed!
How do i register and then if i want to use triggerscriptevent how do i do that?

Thanks if you help!
X Light X

**Comment by Sainan** [comment]
1. `*script_global(...).at(...).as<int*>() = ...;`
2. Have a look at pointers.hpp, pointers.cpp, hooking.hpp, & hooking.cpp.

**Comment by ghost** [comment]
Thank you I am going to take a look if i got it i close it!

**Comment by ghost** [comment]
Well thank you i have now no errors with the script_global and i am going to try it a another time with the hooking!
Thank you!

It's cool that you answered me because many people are like no i dont want to help you!
But you helped me out!
Thank you!
